name: Antibruteforce tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GO111MODULE: "on"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test
